name: ci

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test test/Yapoml.Test/Yapoml.Test.csproj -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release --no-build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nupkgs
        path: '**/*.nupkg'
