name: CI

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release --no-build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nupkgs
        path: '**/*.nupkg'
    - name: Benchmark
      run: dotnet run -c Release --project test/Yapoml.Framework.Benchmark --no-build
        
  myget:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Push
      run: dotnet nuget push **\*.nupkg -s 'https://www.myget.org/F/yapoml/api/v2/package' -k ${{secrets.MYGET_API_KEY}}
